package lixco.com.interfaces;

import java.util.List;

import lixco.com.reportInfo.BangKeChiTietHoaDon;
import lixco.com.reportInfo.BangKeHoaDon;
import lixco.com.reportInfo.BangKeKhoiLuongVanChuyen;
import lixco.com.reportInfo.BangKeKhoiLuongVanChuyenTheoKhachHang;
import lixco.com.reportInfo.BangKeKhoiLuongVanChuyenTheoNVVC;
import lixco.com.reportInfo.BangKeSanPhamChuaGiao;
import lixco.com.reportInfo.BaoCaoHopGiaoBan;
import lixco.com.reportInfo.BaoCaoLever;
import lixco.com.reportInfo.ChiTietCongNo;
import lixco.com.reportInfo.CongNo;
import lixco.com.reportInfo.DoanhThuKhachHangTheoThang;
import lixco.com.reportInfo.LuyKeNhapXuat;
import lixco.com.reportInfo.NhapXuatNgay;
import lixco.com.reportInfo.SoLieuBaoCaoTongHop;
import lixco.com.reportInfo.TheKhoSanPham;
import lixco.com.reportInfo.TheoDoiDoanhThuKhachHang;
import lixco.com.reportInfo.ThongKeSanLuongDoanhThu;
import lixco.com.reportInfo.ThongKeTheoThang;
import lixco.com.reportInfo.TonKhoDauThang;
import lixco.com.reportInfo.TonKhoSanPham;
import lixco.com.reportInfo.TonKhoThang;
import lixco.com.reportInfo.TongKetTieuThuKhachHang;
import lixco.com.reportInfo.TongKetXuatSanPhamTheoQuocGia;
import lixco.com.reportInfo.TongKetXuatTheoBrandName;
import lixco.com.reportInfo.TongKetXuatTheoKhachHang;
import lixco.com.reportInfo.TongKetXuatTheoSanPhamTongKetTieuThuLoai1;
import lixco.com.reportInfo.TongKetXuatTheoSanPhamTongKetTieuThuLoai1Excel;
import lixco.com.reportInfo.TongKetXuatTheoSanPhamTongKetTieuThuLoai2;
import lixco.com.reportInfo.TongKetXuatTheoSanPhamTongKetTieuThuLoai2Excel;
import lixco.com.reportInfo.TongKetXuatTheoSanPhamTongKetTieuThuLoai3;
import lixco.com.reportInfo.TongKetXuatTheoSanPhamTongKetTieuThuLoai3Excel;
import lixco.com.reportInfo.TongKetXuatTheoThanhPhoTongKetTieuThu;

public interface IReportService {
	public int reportTongKetXuatTheoSanPhamTongKetTieuThuLoai1(String json,List<TongKetXuatTheoSanPhamTongKetTieuThuLoai1> list);
	public int reportTongKetXuatTheoSanPhamTongKetTieuThuLoai1Excel(String json,List<TongKetXuatTheoSanPhamTongKetTieuThuLoai1Excel> list);
	public int reportTongKetXuatTheoSanPhamTongKetTieuThuLoai2Excel(String json,List<TongKetXuatTheoSanPhamTongKetTieuThuLoai2Excel> list);
	public int reportTongKetXuatTheoSanPhamTongKetTieuThuLoai3Excel(String json,List<TongKetXuatTheoSanPhamTongKetTieuThuLoai3Excel> list);
	public int reportTongKetXuatTheoSanPhamTongKetTieuThuLoai2(String json,List<TongKetXuatTheoSanPhamTongKetTieuThuLoai2> list);
	public int reportTongKetXuatTheoSanPhamTongKetTieuThuLoai3(String json,List<TongKetXuatTheoSanPhamTongKetTieuThuLoai3> list);
	public int reportTongKetCongNoKhachHang(String json,List<TongKetXuatTheoKhachHang> list);
	public int reportTongKetTieuThuKhachHang(String json,List<TongKetTieuThuKhachHang> list);
	public int reportTongKetTieuThuKhachHangDVT(String json,List<TongKetTieuThuKhachHang> list);
	public int reportTheoDoiDoanhThuKhachHang(String json,List<TheoDoiDoanhThuKhachHang> list);
	public int reportTongKetXuatTheoThanhPho(String json,List<TongKetXuatTheoThanhPhoTongKetTieuThu> list);
	public int reportTongKetXuatSanPhamTheoQuocGia(String json,List<TongKetXuatSanPhamTheoQuocGia> list);
	public int reportTongKetXuatTheoBrandName(String json,List<TongKetXuatTheoBrandName> list);
	public int reportBangKeHoaDon(String json,List<BangKeHoaDon> list);
	public int reportCongNo(String json,List<CongNo> list);
	public int reportChiTietCongNo(String json,List<ChiTietCongNo> list);
	public int reportThongKeSanLuongDoanhThu(String json,List<ThongKeSanLuongDoanhThu> list);
	public int reportThongKeTheoThang(String json,List<ThongKeTheoThang> list);
	public int reportTonKhoThang(String json,List<TonKhoThang> list);
	public int reportTonKhoSanPham(String json,List<TonKhoSanPham> list);
	public int reportTheKhoSanPham(String json,List<TheKhoSanPham> list);
	public int reportTheKhoSanPhamDVT(String json,List<TheKhoSanPham> list);
	public int reportDoanhThuTheoThang(String json,List<DoanhThuKhachHangTheoThang> list);
	public int reportBangKeChiTietHoaDon(String json,List<BangKeChiTietHoaDon> list);
	public int reportNhapXuatTheoNgay(String json,List<NhapXuatNgay> list);
	public int reportBangKeKhoiLuongVanChuyen(String json,List<BangKeKhoiLuongVanChuyen> list);
	public int reportBangKeKhoiLuongVanChuyenTheoKhachHang(String json,List<BangKeKhoiLuongVanChuyenTheoKhachHang> list);
	public int reportBangKeKhoiLuongVanChuyenTheoNVVC(String json,List<BangKeKhoiLuongVanChuyenTheoNVVC> list);
//	public int reportBangKeChiPhiVanChuyenPhaiTraNeuThueXeNgoai(String json,List<BangKeChi>);
//	public int reportXemDoanhThuVaSanLuong(String json,List<DoanhThuVaSanLuong> list);
//	public int reportBaoCaoHopGiaoBan(String json,List<?> list);
	public int reportBaoCaoLever(String json,List<BaoCaoLever> list);
	public int reportLaySoLieuBaoCaoTongHop(String json, List<SoLieuBaoCaoTongHop> list,boolean tachcombo);
	public int reportLaySoLieuBaoCaoTongHopcu(String json, List<SoLieuBaoCaoTongHop> list,boolean tachcombo);
	public int reportInLuyKeXuatNhap(String json,List<LuyKeNhapXuat> list);
	public TonKhoDauThang reportTonKhoDauThang(int month, int year, long product_id);
	public TonKhoDauThang reportTonKhoDauThangDVT(int month, int year, long product_id);
	
	public int reportBaoCaoHopGiaoBan(String json, List<BaoCaoHopGiaoBan> list);
	public int reportBangKeSanPhamChuaGiao(String json, List<BangKeSanPhamChuaGiao> list) ;
	public List<Object[]> reportLaySoLieuBaoCaoTongHop2(String json);
	}
